// CFO Daily Brief: aggregates per-tenant CFO snapshot and emails via Resend.
// Triggered by pg_cron at 07:00 daily.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

import { buildCors } from "../_shared/cors.ts";
let corsHeaders: Record<string, string> = buildCors();
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

const fmt = (n: number) =>
  new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 })
    .format(n || 0);

function buildEmail(t: {
  cashPosition: number; receivablesTotal: number; receivablesOverdue: number;
  payablesTotal: number; revenueMTD: number; date: string;
}) {
  return `
  <div style="font-family:Inter,Arial,sans-serif;max-width:560px;margin:0 auto;background:#fff;color:#0f172a;">
    <div style="background:linear-gradient(135deg,#0ea5e9,#6366f1);padding:24px;border-radius:12px 12px 0 0;color:#fff;">
      <h2 style="margin:0;font-size:20px;">Daily CFO Brief</h2>
      <div style="opacity:.85;font-size:12px;margin-top:4px;">${t.date}</div>
    </div>
    <div style="padding:20px;border:1px solid #e2e8f0;border-top:0;border-radius:0 0 12px 12px;">
      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <tr><td style="padding:8px 0;color:#64748b;">Cash Position</td><td style="text-align:right;font-weight:600;">${fmt(t.cashPosition)}</td></tr>
        <tr><td style="padding:8px 0;color:#64748b;">Revenue MTD</td><td style="text-align:right;font-weight:600;">${fmt(t.revenueMTD)}</td></tr>
        <tr><td style="padding:8px 0;color:#64748b;">Receivables Total</td><td style="text-align:right;font-weight:600;">${fmt(t.receivablesTotal)}</td></tr>
        <tr><td style="padding:8px 0;color:#b91c1c;">Overdue Receivables</td><td style="text-align:right;font-weight:600;color:#b91c1c;">${fmt(t.receivablesOverdue)}</td></tr>
        <tr><td style="padding:8px 0;color:#64748b;">Open Payables</td><td style="text-align:right;font-weight:600;">${fmt(t.payablesTotal)}</td></tr>
      </table>
      <p style="margin-top:18px;font-size:12px;color:#64748b;">
        Generated by Routeace AI CFO. Open the AI CFO console to review enforcement actions and approvals.
      </p>
    </div>
  </div>`;
}

Deno.serve(async (req) => {
  corsHeaders = buildCors(req);
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  // Cron-only endpoint: require shared secret to prevent unauthenticated triggers
  const cronSecret = Deno.env.get("CRON_SECRET") ?? "";
  const incomingSecret = req.headers.get("x-cron-secret") ?? "";
  if (!cronSecret || incomingSecret !== cronSecret) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), {
      status: 401,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }

  try {
    const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

    // 1) Find paid tenants
    const { data: paid } = await supabase
      .from("billing_accounts")
      .select("tenant_id, billing_email, plan_id")
      .eq("status", "active")
      .not("plan_id", "is", null);

    const tenants = paid || [];

    // LC vs LD module separation: exclude any Logistics Department tenants
    // from the CFO daily brief - financial briefs are LC-only.
    const tenantIds = tenants.map((t: any) => t.tenant_id).filter(Boolean);
    let ldTenantIds = new Set<string>();
    if (tenantIds.length) {
      const { data: orgs } = await supabase
        .from("organizations")
        .select("id, tenant_mode")
        .in("id", tenantIds);
      ldTenantIds = new Set(
        (orgs || [])
          .filter((o: any) => (o.tenant_mode || "").toString().toUpperCase() === "LOGISTICS_DEPARTMENT")
          .map((o: any) => o.id),
      );
    }

    const today = new Date().toISOString().slice(0, 10);
    const monthStart = new Date(); monthStart.setDate(1); monthStart.setHours(0,0,0,0);
    const monthStartISO = monthStart.toISOString().slice(0, 10);

    let sent = 0, failed = 0, skippedLD = 0;

    for (const t of tenants) {
      if (ldTenantIds.has(t.tenant_id)) { skippedLD++; continue; }
      const recipient = t.billing_email;
      if (!recipient) { failed++; continue; }


      const [arRes, apRes, invRes] = await Promise.all([
        supabase.from("accounts_receivable").select("balance, due_date, status").eq("organization_id", t.tenant_id),
        supabase.from("accounts_payable").select("balance, status").eq("organization_id", t.tenant_id),
        supabase.from("invoices").select("total_amount, invoice_date, status").eq("organization_id", t.tenant_id).gte("invoice_date", monthStartISO),
      ]);

      const ar = arRes.data || [];
      const ap = apRes.data || [];
      const inv = invRes.data || [];

      const receivablesTotal = ar.reduce((s: number, r: any) => s + Number(r.balance || 0), 0);
      const receivablesOverdue = ar
        .filter((r: any) => r.due_date && r.due_date < today && r.status !== "paid")
        .reduce((s: number, r: any) => s + Number(r.balance || 0), 0);
      const payablesTotal = ap
        .filter((r: any) => r.status !== "paid")
        .reduce((s: number, r: any) => s + Number(r.balance || 0), 0);
      const revenueMTD = inv
        .filter((r: any) => r.status !== "cancelled")
        .reduce((s: number, r: any) => s + Number(r.total_amount || 0), 0);

      const snap = {
        cashPosition: revenueMTD - payablesTotal,
        receivablesTotal, receivablesOverdue, payablesTotal, revenueMTD,
        date: new Date().toLocaleDateString("en-NG", { dateStyle: "full" }),
      };

      // 2) Send via Resend
      let status = "queued", errorMsg: string | null = null, msgId: string | null = null;
      if (RESEND_API_KEY) {
        try {
          const r = await fetch("https://api.resend.com/emails", {
            method: "POST",
            headers: {
              "Authorization": `Bearer ${RESEND_API_KEY}`,
              "Content-Type": "application/json",
            },
            body: JSON.stringify({
              from: "Routeace CFO <onboarding@resend.dev>",
              to: [recipient],
              subject: `Daily CFO Brief - ${snap.date}`,
              html: buildEmail(snap),
            }),
          });
          const j = await r.json();
          if (r.ok) { status = "sent"; msgId = j.id || null; sent++; }
          else { status = "failed"; errorMsg = JSON.stringify(j); failed++; }
        } catch (e) {
          status = "failed"; errorMsg = (e as Error).message; failed++;
        }
      }

      await supabase.from("cfo_brief_log").insert({
        tenant_id: t.tenant_id,
        recipient_email: recipient,
        cash_position: snap.cashPosition,
        receivables_total: snap.receivablesTotal,
        receivables_overdue: snap.receivablesOverdue,
        payables_total: snap.payablesTotal,
        revenue_mtd: snap.revenueMTD,
        status,
        error: errorMsg,
        resend_message_id: msgId,
      });
    }

    return new Response(JSON.stringify({ ok: true, tenants: tenants.length, sent, failed, skipped_ld: skippedLD }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    return new Response(JSON.stringify({ error: msg }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
