import { useState } from "react";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { motion } from "framer-motion";
import { Lightbulb } from "lucide-react";

export interface BusinessProfile {
  industry: string;
  targetMarkets: string;
  fleetType: string;
  revenueTarget12m: string;
  currentMonthlyRevenue: string;
  profitMarginTarget: string;
  growthAmbition: string;
  visionStatement: string;
}

interface BusinessProfileStepProps {
  data: BusinessProfile;
  onChange: (data: BusinessProfile) => void;
}

const FLEET_TYPES = [
  "Heavy Trucks (15T+)",
  "Light Trucks (5-10T)",
  "Bikes & Vans",
  "Mixed Fleet",
  "Trailers Only",
];

const GROWTH_AMBITIONS = [
  "Steady & Sustainable",
  "Aggressive Growth",
  "Market Domination",
  "Regional Expansion",
  "National Scale",
];

function generateAutoVision(profile: BusinessProfile): string {
  const industry = profile.industry || "logistics";
  const market = profile.targetMarkets || "our region";
  const fleet = profile.fleetType || "our fleet";

  return `To be the most trusted and technology-driven ${industry.toLowerCase()} company in ${market}, delivering excellence through ${fleet.toLowerCase()} operations while creating sustainable value for our customers, drivers, and investors.`;
}

const BusinessProfileStep = ({ data, onChange }: BusinessProfileStepProps) => {
  const [autoGenerated, setAutoGenerated] = useState(false);

  const update = (key: keyof BusinessProfile, value: string) => {
    onChange({ ...data, [key]: value });
  };

  const handleAutoVision = () => {
    const vision = generateAutoVision(data);
    onChange({ ...data, visionStatement: vision });
    setAutoGenerated(true);
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      className="space-y-5"
    >
      <div className="text-center mb-6">
        <h2 className="text-2xl font-bold">Business Profile</h2>
        <p className="text-muted-foreground mt-1">
          Help us understand your business so we can build your strategic vision
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="space-y-2">
          <Label>Industry</Label>
          <Input
            placeholder="e.g. Logistics & Haulage"
            value={data.industry}
            onChange={(e) => update("industry", e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <Label>Target Markets</Label>
          <Input
            placeholder="e.g. Nigeria, West Africa"
            value={data.targetMarkets}
            onChange={(e) => update("targetMarkets", e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <Label>Fleet Type</Label>
          <Select value={data.fleetType} onValueChange={(v) => update("fleetType", v)}>
            <SelectTrigger><SelectValue placeholder="Select fleet type" /></SelectTrigger>
            <SelectContent>
              {FLEET_TYPES.map((t) => (
                <SelectItem key={t} value={t}>{t}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label>Growth Ambition</Label>
          <Select value={data.growthAmbition} onValueChange={(v) => update("growthAmbition", v)}>
            <SelectTrigger><SelectValue placeholder="Select ambition" /></SelectTrigger>
            <SelectContent>
              {GROWTH_AMBITIONS.map((g) => (
                <SelectItem key={g} value={g}>{g}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="space-y-2">
          <Label>12-Month Revenue Target</Label>
          <Input
            placeholder="e.g. 500,000,000"
            value={data.revenueTarget12m}
            onChange={(e) => update("revenueTarget12m", e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <Label>Current Monthly Revenue</Label>
          <Input
            placeholder="e.g. 25,000,000"
            value={data.currentMonthlyRevenue}
            onChange={(e) => update("currentMonthlyRevenue", e.target.value)}
          />
        </div>
        <div className="space-y-2">
          <Label>Profit Margin Target (%)</Label>
          <Input
            placeholder="e.g. 15"
            value={data.profitMarginTarget}
            onChange={(e) => update("profitMarginTarget", e.target.value)}
          />
        </div>
      </div>

      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label>Vision Statement (optional)</Label>
          {!data.visionStatement && (
            <button
              type="button"
              onClick={handleAutoVision}
              className="text-xs text-primary flex items-center gap-1 hover:underline"
            >
              <Lightbulb className="w-3 h-3" />
              Auto-generate
            </button>
          )}
        </div>
        <Textarea
          placeholder="Leave blank and we'll generate one for you..."
          value={data.visionStatement}
          onChange={(e) => {
            update("visionStatement", e.target.value);
            setAutoGenerated(false);
          }}
          rows={3}
        />
        {autoGenerated && (
          <p className="text-xs text-muted-foreground">✨ Auto-generated based on your inputs</p>
        )}
      </div>
    </motion.div>
  );
};

export default BusinessProfileStep;
