INSERT INTO public.billing_plans (
  plan_code,
  plan_name,
  pricing_model,
  base_price,
  price_per_drop,
  price_per_api_call,
  currency,
  included_drops,
  included_api_calls,
  max_users,
  max_vehicles,
  billing_cycle,
  is_active,
  features
) VALUES
  (
    'logistics_dept_foundation',
    'Logistics Department Foundation',
    'flat',
    150000,
    0,
    0,
    'NGN',
    0,
    0,
    5,
    NULL,
    'monthly',
    true,
    '{"tenant_mode":"LOGISTICS_DEPARTMENT","included_users":5,"extra_user_price":10000,"core_transport":true,"dispatch_tracking":true,"fleet_management":true,"vendor_management":"basic","sla_tracking":true,"operations_dashboard":true}'::jsonb
  ),
  (
    'logistics_dept_growth',
    'Logistics Department Growth',
    'flat',
    350000,
    0,
    0,
    'NGN',
    0,
    0,
    15,
    NULL,
    'monthly',
    true,
    '{"tenant_mode":"LOGISTICS_DEPARTMENT","included_users":15,"extra_user_price":7500,"everything_in_foundation":true,"ai_dispatch_optimization":true,"vendor_rate_card_upload":true,"cost_comparison_ai":true,"vendor_payout_engine":"basic","maintenance_intelligence":true,"performance_dashboards":true}'::jsonb
  ),
  (
    'logistics_dept_enterprise',
    'Logistics Department Enterprise',
    'flat',
    1200000,
    0,
    0,
    'NGN',
    0,
    0,
    50,
    NULL,
    'monthly',
    true,
    '{"tenant_mode":"LOGISTICS_DEPARTMENT","included_users":50,"extra_user_price":5000,"everything_in_growth":true,"ai_cfo":true,"vendor_performance_intelligence":true,"autonomous_dispatch_rebalancing":true,"multi_warehouse_region":true,"erp_wms_integrations":true,"approval_workflows":true,"sales_department_tracking_portal":true}'::jsonb
  )
ON CONFLICT (plan_code) DO UPDATE SET
  plan_name = EXCLUDED.plan_name,
  pricing_model = EXCLUDED.pricing_model,
  base_price = EXCLUDED.base_price,
  price_per_drop = EXCLUDED.price_per_drop,
  price_per_api_call = EXCLUDED.price_per_api_call,
  currency = EXCLUDED.currency,
  included_drops = EXCLUDED.included_drops,
  included_api_calls = EXCLUDED.included_api_calls,
  max_users = EXCLUDED.max_users,
  max_vehicles = EXCLUDED.max_vehicles,
  billing_cycle = EXCLUDED.billing_cycle,
  is_active = EXCLUDED.is_active,
  features = EXCLUDED.features,
  updated_at = now();