
-- Execution tasks generated by AOE
CREATE TABLE public.execution_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  decision_id UUID REFERENCES public.autonomous_decisions(id) ON DELETE SET NULL,
  task_type TEXT NOT NULL DEFAULT 'general',
  target_module TEXT NOT NULL,
  assigned_role TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  priority_score NUMERIC DEFAULT 50,
  risk_level TEXT DEFAULT 'low',
  status TEXT NOT NULL DEFAULT 'pending',
  payload JSONB DEFAULT '{}',
  result JSONB,
  assigned_to UUID,
  started_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  failed_reason TEXT,
  is_rollback_possible BOOLEAN DEFAULT true,
  rolled_back_at TIMESTAMPTZ,
  tenant_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.execution_tasks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leadership can view execution tasks"
  ON public.execution_tasks FOR SELECT TO authenticated
  USING (
    public.has_role(auth.uid(), 'super_admin') OR
    public.has_role(auth.uid(), 'admin') OR
    public.has_role(auth.uid(), 'org_admin') OR
    public.has_role(auth.uid(), 'finance_manager') OR
    public.has_role(auth.uid(), 'ops_manager')
  );

CREATE POLICY "Admins can manage execution tasks"
  ON public.execution_tasks FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'super_admin') OR
    public.has_role(auth.uid(), 'admin')
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'super_admin') OR
    public.has_role(auth.uid(), 'admin')
  );

-- Execution outcomes / audit
CREATE TABLE public.execution_outcomes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  task_id UUID REFERENCES public.execution_tasks(id) ON DELETE CASCADE,
  decision_id UUID REFERENCES public.autonomous_decisions(id) ON DELETE SET NULL,
  outcome_type TEXT NOT NULL DEFAULT 'success',
  value_impact_amount NUMERIC DEFAULT 0,
  currency TEXT DEFAULT 'NGN',
  time_saved_minutes INTEGER DEFAULT 0,
  risk_prevented BOOLEAN DEFAULT false,
  risk_description TEXT,
  error_details TEXT,
  rollback_performed BOOLEAN DEFAULT false,
  self_healed BOOLEAN DEFAULT false,
  healing_details TEXT,
  verified_by UUID,
  verified_at TIMESTAMPTZ,
  tenant_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.execution_outcomes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Leadership can view execution outcomes"
  ON public.execution_outcomes FOR SELECT TO authenticated
  USING (
    public.has_role(auth.uid(), 'super_admin') OR
    public.has_role(auth.uid(), 'admin') OR
    public.has_role(auth.uid(), 'org_admin') OR
    public.has_role(auth.uid(), 'finance_manager') OR
    public.has_role(auth.uid(), 'ops_manager')
  );

CREATE POLICY "Admins can manage execution outcomes"
  ON public.execution_outcomes FOR ALL TO authenticated
  USING (
    public.has_role(auth.uid(), 'super_admin') OR
    public.has_role(auth.uid(), 'admin')
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'super_admin') OR
    public.has_role(auth.uid(), 'admin')
  );

-- Indexes
CREATE INDEX idx_execution_tasks_status ON public.execution_tasks(status);
CREATE INDEX idx_execution_tasks_decision ON public.execution_tasks(decision_id);
CREATE INDEX idx_execution_tasks_module ON public.execution_tasks(target_module);
CREATE INDEX idx_execution_outcomes_task ON public.execution_outcomes(task_id);
CREATE INDEX idx_execution_outcomes_type ON public.execution_outcomes(outcome_type);

-- Timestamp trigger
CREATE TRIGGER update_execution_tasks_updated_at
  BEFORE UPDATE ON public.execution_tasks
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
